export const USER_STATE_CHANGE = "USER_STATE_CHANGE"
export const CURRENT_USER_POSTS_UPDATE = "CURRENT_USER_POSTS_UPDATE"
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
